{% set name = "champ" %}
{% set version = "2.1.0" %}
{% set sha256 = "e4483770196c389800fb771721df0e29b008cb39837a94ee215690b51f71a7cb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0
  noarch: python


requirements:

  host:
    - python
    - igraph
    - setuptools
    - pip

  run:
    - python
    - python-igraph
    - matplotlib
    - numpy >=1.13
    - scipy >=0.19
    - pandas
    - h5py
    - seaborn
    - tqdm
    - louvain
    - leidenalg
    - scikit-learn
    - future


test:
  imports:
    - champ

about:
  home: https://github.com/wweir827/CHAMP
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A modularity based tool for screening a set of partitions.'
  description: |
    Modularity based community detection for networks and filtering
    based presence of domain of optimality within the resolution space.
  doc_url: https://champ.readthedocs.io/en/latest

extra:
  recipe-maintainers: 
    - wweir827
