travis:
  secure:
    BINSTAR_TOKEN: lNaDtWmEoKrCJsbI3UsLQRq2TWouR3tz59RPTYsCPq/7KXTFyAWUCc7PJ6etAtkCzHLyXltFsDlAgJT0Rj3PBwfXfzTunJMh9tVt5H3YoH+4N0IOe71xS1J7J3JepmS09Yc1CS01WAVfd/IK8CFFlIB+fNrYSAq6tbPamcjJFO/4HjOJmoWRLNljKYrUiV5cQtQVXMFi94aYqOGXp0j/RJbpppYOqIEATZxH6Tht7EC5zoQudeiEBL6Rl/Yn3lVHa6wKtHj2pBnF2234WeEP72g39NbxPBMF1BgnR/VuQlowBYemi+xdqR6jksVuD9Qh1UN/WbCZDuLzyutZzPZYsn16mrARzGdqS4OaMJYlrCay+OdEdeDS8NYBFODQ/kv5VRIjWxZLgl5ezkjqRWmnUfx+w/5g6Lco36bpmIWPesaXoKipC4FP96ATE6W08tbKz1hM11HremZqlLYCPj0umUyv8KW03Uh24zXUnPOIZJU6IHllL9/EsLrlyOQLmwEvw/mbpsZWdLhQlKzgWI8/by1/9szp8axfoSbbc2rU4enmBRFBAN6DJ/WiOvnY+UMeg5kgz2Fz1w7KQZSxw7zmtAgwj4Mws9mxaJjxn4CTPR5s1N04I0HYUri20N7/7K/MPs8oqJNbGPkFCpBydAX6NlOEIOlfjUeasI+AwejS9uU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
